name: GitHub Activity

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Update stats graphics
        run: |
          curl "https://tuunit-github-readme-stats.vercel.app/api?username=tuunit&custom_title=Jan%20Larwig&theme=dark&show_icons=true&card_width=450&icon_color=2596be&ring_color=2596be&include_all_commits=true&count_private=true&hide=stars&disable_animations=true" > general_dark.svg
          curl "https://tuunit-github-readme-stats.vercel.app/api?username=tuunit&custom_title=Jan%20Larwig&show_icons=true&card_width=450&icon_color=2596be&ring_color=2596be&include_all_commits=true&count_private=true&hide=stars&disable_animations=true" > general_light.svg
      - name: Commit stats graphics
        uses: EndBug/add-and-commit@v9
        with:
          add: ./*.svg
          message: Update github-readme-stats
          default_author: github_actions
      - name: Update GitHub Activity Readme
        uses: tuunit/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
